# FROM python:3.12

# LABEL maintainer="saqibmurtazakhan@gmail.com"

# WORKDIR /app

# RUN apt-get update && apt-get install -y \
#     build-essential \
#     libpq-dev \
#     protobuf-compiler \
#     && rm -rf /var/lib/apt/lists/*

# RUN pip install poetry

# COPY pyproject.toml poetry.lock /app/

# RUN poetry config virtualenvs.create false

# RUN poetry install --no-root

# COPY fastapi_1 /app/fastapi_1


# # Ensure the protos directory is in the PYTHONPATH
# ENV PYTHONPATH="/app/protos_file:${PYTHONPATH}"

# EXPOSE 8006

# CMD ["poetry", "run", "uvicorn", "fastapi_1.main:app", "--host", "0.0.0.0", "--port", "8006", "--reload"]

FROM python:3.12

LABEL maintainer="saqibmurtazakhan@gmail.com"

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    protobuf-compiler \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry

COPY pyproject.toml poetry.lock /app/

RUN poetry config virtualenvs.create false

RUN poetry install --no-root

COPY fastapi_1 /app/fastapi_1

# Install Dapr CLI
RUN wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash

# Ensure the protos directory is in the PYTHONPATH
ENV PYTHONPATH="/app/protos_file:${PYTHONPATH}"

EXPOSE 8000

CMD ["poetry", "run", "uvicorn", "fastapi_1.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
