FROM python:3.12

LABEL maintainer="saqibmurtazakhan@gmail.com"

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    protobuf-compiler \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry

COPY pyproject.toml poetry.lock /app/

RUN poetry config virtualenvs.create false

RUN poetry install --no-root

COPY fastapi_2 /app/fastapi_2

# Ensure the protos directory is in the PYTHONPATH
ENV PYTHONPATH="/app/protos_file:${PYTHONPATH}"

EXPOSE 8007

CMD ["poetry", "run", "uvicorn", "fastapi_2.main:app", "--host", "0.0.0.0", "--port", "8007", "--reload"]
