# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\x03\x61pi\"\x9e\x01\n\tInventory\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\titem_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\nunit_price\x18\x04 \x01(\x02\x12\x10\n\x08quantity\x18\x05 \x01(\x05\x12\x15\n\rstock_in_hand\x18\x06 \x01(\x05\x12\x11\n\tthreshold\x18\x07 \x01(\x05\x12\r\n\x05\x65mail\x18\x08 \x01(\t\"C\n\x10InventoryUpdates\x12\x11\n\toperation\x18\x01 \x01(\t\x12\x1c\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x0e.api.Inventoryb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INVENTORY._serialized_start=25
  _INVENTORY._serialized_end=183
  _INVENTORYUPDATES._serialized_start=185
  _INVENTORYUPDATES._serialized_end=252
# @@protoc_insertion_point(module_scope)
