FROM python:3.12

LABEL maintainer="saqibmurtazakhan@gmail.com"

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry

COPY pyproject.toml poetry.lock /app/

RUN poetry config virtualenvs.create false

RUN poetry install --no-root

COPY api_2 /app/api_2

EXPOSE 8000

CMD ["poetry", "run", "uvicorn", "api_2.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
