FROM python:3.12

LABEL maintainer="saqibmurtazakhan@gmail.com"

WORKDIR /app

RUN apt-get update && apt-get install -y \
build-essential \
libpq-dev \
protobuf-compiler \
&& rm -rf /var/lib/apt/lists/*

RUN pip install poetry

COPY pyproject.toml poetry.lock /app/

RUN poetry config virtualenvs.create false

RUN poetry install

COPY user_service /app/user_service

EXPOSE 8009

CMD [ "poetry", "run", "uvicorn", "user_service.main:app", "--host", "0.0.0.0", "--port", "8009", "--reload" ]

